/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current authenticated user
         * @description Bootstrap call on app launch. A valid Firebase token with no matching BuryMe user returns `404`, signalling the client to route into registration.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision a BuryMe user on first login
         * @description Phone/email identity comes from the verified Firebase token, not the body. §12.2.1 display-name constraints apply. Returns `409` if a profile already exists for this identity.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or refresh a device FCM token (§11.1.3) */
        post: operations["registerFcmToken"];
        /** Remove a device FCM token (per-device logout) */
        delete: operations["deleteFcmToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search registered, verified users (§6.1.3)
         * @description Supports lookup by display name, phone, or email (§7.1.3). Returns only verified, registered accounts. Min 2 / max 100 characters (§12.2.1).
         */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's public profile summary */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own profile (§6.1.2)
         * @description Display name and/or profile photo. §12.2.1 constraints apply.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/users/me/telebirr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own Telebirr verification status (§8.4) */
        get: operations["getTelebirr"];
        put?: never;
        /**
         * Register / re-verify a Telebirr number (§6.1.6)
         * @description Prompted contextually, not at registration. Updating the number resets status to Unverified until re-verified (§7.1.6). §12.2.1 format constraints apply.
         */
        post: operations["verifyTelebirr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/telebirr/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send (or resend) a verification code to the saved Telebirr number
         * @description Sends a fresh 6-digit one-time code by SMS to the `telebirr_number` recorded via `POST /users/me/telebirr`. Codes expire after 5 minutes; a new code may be requested at most once per 60 seconds and replaces any earlier one. Ownership of a Telebirr number is proven by receiving this SMS — Chapa's integration does not verify account ownership.
         */
        post: operations["sendTelebirrOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/telebirr/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the Telebirr verification code
         * @description Checks the code against the pending challenge. On success the account becomes `Verified` and `verified_at` is set. Five wrong attempts invalidate the challenge; request a new code with `POST /users/me/telebirr/otp`.
         */
        post: operations["confirmTelebirrOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List requests involving the current user */
        get: operations["listRequests"];
        put?: never;
        /**
         * Create a Borrow, Lend, or Repayment request
         * @description Body shape is discriminated by `request_type`. See `BorrowRequestInput` / `LendRequestInput` / `RepaymentRequestInput`. §12.2.2 validation applies per type. A user cannot target themselves, and Borrow/Lend cannot be created while an open request already exists between the same two users in the same direction (§7.1.3, §12.2.2).
         */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a request */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}/counter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the single allowed counter-proposal
         * @description Negotiation is capped at two proposals total (§6.2.1): the original, then one counter. Allowed only while `status = Pending`, and only once — a second counter attempt returns `409 STATUS_CONFLICT`. After a counter, only the original initiator may accept or decline; the counter-submitter cannot counter again.
         */
        post: operations["counterRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept the current terms
         * @description For Borrow/Lend: creates the Obligation and sets `request.obligation_id`. The obligation enters `Active` immediately if `disbursement_method = Already Given`, or `Pending Disbursement` if `Through App` (§6.3.1). For Borrow specifically, `disbursement_method` is supplied by the lender at acceptance (§8.5) — see `AcceptBorrowRequestInput`. For Repayment: marks the request `Accepted`; the actual balance update happens when the resulting payment is confirmed, not here.
         */
        post: operations["acceptRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline the request */
        post: operations["declineRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw a request (initiator only, while Pending) */
        post: operations["cancelRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List obligations for the current user */
        get: operations["listObligations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an obligation */
        get: operations["getObligation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/disburse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lender starts a Through-App disbursement (§6.3.1, §11.1.1)
         * @description Valid only from `Pending Disbursement`, lender only. Creates a `Disbursement` / `Chapa` Payment (`Pending Acknowledgement`) and opens a Chapa checkout session for the **lender** to pay the principal in (collection hop) — the client redirects the lender to `checkout_url`. When the checkout webhook confirms the funds, the backend triggers the Transfer hop to the borrower's verified Telebirr; when the transfer webhook confirms, the obligation becomes `Active` with `outstanding_balance = principal_amount`. Until then it stays `Pending Disbursement`. A `Failed` payment may be retried by calling this again.
         */
        post: operations["disburseObligation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/repayment-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convenience wrapper — create a Repayment request against this obligation
         * @description Equivalent to `POST /requests` with `request_type: Repayment` and `obligation_id` pre-filled from the path. Restricted to currently-overdue amounts only (§6.2.2, §12.2.2) — a deliberate escalation distinct from automated reminders (§13.3).
         */
        post: operations["createRepaymentRequestForObligation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the repayment schedule and installments
         * @description Present only for `repayment_type = Installments` obligations.
         */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payment history for an obligation (§6.4.3) */
        get: operations["listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/payments/chapa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate a Chapa-mediated payment
         * @description Both directions open a Chapa checkout session for the payer (collection hop; the transfer to the recipient follows on webhook confirmation): `Repayment` collects from the borrower and pays the lender, `Disbursement` collects from the lender and pays the borrower. Prefer `POST /obligations/{id}/disburse` for the latter — it is the same operation under a clearer name; this endpoint exists so both directions share one Payments interface. Amount is never free-entered — it is the obligation's principal, full outstanding balance, or the selected installment's amount (§6.4.1, §12.2.4). Requires the recipient to have a verified Telebirr account, or returns `409 RECIPIENT_UNVERIFIED`.
         */
        post: operations["initiateChapaPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/payments/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a payment completed outside the platform (§6.4.2)
         * @description Symmetric — either party may record, for either direction. Enters `Pending Acknowledgement` until the counterparty confirms or disputes. Amount is system-set, never free-entered (§12.2.4).
         */
        post: operations["recordExternalPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a recorded external payment
         * @description Updates the obligation's outstanding balance on confirmation (§6.4.3).
         */
        post: operations["acknowledgePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispute a recorded external payment */
        post: operations["disputePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/chapa/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chapa checkout (collection) confirmation callback
         * @description Server-to-server; not called by clients. Signature-verified before any state change is applied (§11.1.1, §10.2). On confirmation, funds are in BuryMe's merchant balance and the backend proceeds to the Transfer hop — to the borrower for a `Disbursement` payment, to the lender for a `Repayment`. The Payment stays `Pending Acknowledgement` until the transfer webhook confirms; a failed checkout marks it `Failed`.
         */
        post: operations["chapaCheckoutWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/chapa/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chapa transfer (payout) confirmation callback
         * @description Server-to-server. On confirmation the payment is marked `Confirmed` and, for a disbursement, the obligation moves `Pending Disbursement → Active`.
         */
        post: operations["chapaTransferWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group expenses involving the current user */
        get: operations["listGroupExpenses"];
        put?: never;
        /**
         * Record a group expense and spawn per-participant obligations
         * @description Creates one bilateral Obligation per participant for their assigned share. No obligation is ever created for the payer's own share, even when `payer_share_included` is true (§8.12). Constraints: 1–50 participants, amounts must sum to the total within 0.01 ETB tolerance (§12.2.2). Each spawned obligation is `Lump Sum` / `Already Given` and `Active` from creation (the payer has already settled the bill), with `outstanding_balance` equal to that participant's assigned share and `due_date` taken from the input.
         */
        post: operations["createGroupExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-expenses/{groupExpenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a group expense and its participants */
        get: operations["getGroupExpense"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List settlement suggestions involving the current user */
        get: operations["listSettlementSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/suggestions/{suggestionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a settlement suggestion */
        get: operations["getSettlementSuggestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/suggestions/{suggestionId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a settlement suggestion
         * @description Records this user's response. The suggestion's aggregate `status` becomes `Accepted` — and both obligations move to `Settled` — only once both `user_id_a_response` and `user_id_b_response` are `Accepted` (§8.14).
         */
        post: operations["acceptSettlementSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/suggestions/{suggestionId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline a settlement suggestion
         * @description Either party declining moves the aggregate `status` to `Declined`; obligations remain unchanged.
         */
        post: operations["declineSettlementSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{obligationId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chronological, immutable event log for an obligation */
        get: operations["getObligationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the notification feed */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notifications as read */
        post: operations["markNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update notification preferences (§7.1.5) */
        patch: operations["updateNotificationPreferences"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Standard error codes per §12.3.2.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "DUPLICATE_SUBMISSION" | "STATUS_CONFLICT" | "BALANCE_EXCEEDED" | "CONCURRENT_MODIFICATION" | "PAYMENT_GATEWAY_UNAVAILABLE" | "PAYMENT_GATEWAY_ERROR" | "RECIPIENT_UNVERIFIED" | "PARTIAL_WRITE_ROLLED_BACK" | "UNAUTHENTICATED" | "UNAUTHORIZED" | "NOT_FOUND" | "INTERNAL_ERROR";
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Plain-language, user-safe. Never exposes stack traces, DB ids, or raw third-party payloads (§12.1). */
                message: string;
                /** @description Present only for field-level validation errors; omitted for system errors (§12.3.1). */
                field?: string | null;
            };
        };
        /** @enum {string} */
        RequestType: "Borrow" | "Lend" | "Repayment";
        /** @enum {string} */
        RequestStatus: "Pending" | "Countered" | "Accepted" | "Declined" | "Cancelled";
        /** @enum {string} */
        RepaymentType: "Lump Sum" | "Installments";
        /** @enum {string} */
        DisbursementMethod: "Already Given" | "Through App";
        /**
         * @description §8.6. `Pending Disbursement` only when disbursement_method is `Through App`,
         *     between agreement and completed transfer. `Partially Paid` only for
         *     Installments obligations; Lump Sum goes `Active` → `Settled` directly.
         * @enum {string}
         */
        ObligationStatus: "Pending Disbursement" | "Active" | "Partially Paid" | "Settled" | "Disputed";
        /** @enum {string} */
        InstallmentStatus: "Pending" | "Paid" | "Overdue";
        /** @enum {string} */
        ScheduleStatus: "Active" | "Completed";
        /** @enum {string} */
        PaymentDirection: "Disbursement" | "Repayment";
        /** @enum {string} */
        PaymentMethod: "Chapa" | "External";
        /**
         * @description Method used for an externally-recorded payment (§12.2.4).
         * @enum {string}
         */
        ExternalPaymentMethodNote: "Cash" | "Bank Transfer" | "Mobile Money" | "Other";
        /** @enum {string} */
        PaymentStatus: "Pending Acknowledgement" | "Confirmed" | "Disputed" | "Failed";
        /** @enum {string} */
        TelebirrStatus: "Unverified" | "Verified";
        /** @enum {string} */
        SettlementResponse: "Pending" | "Accepted" | "Declined";
        /** @enum {string} */
        ObligationHistoryEventType: "Created" | "Payment Confirmed" | "Terms Changed" | "Schedule Accepted" | "Settled" | "Disputed";
        /** @enum {string} */
        NotificationReferenceType: "Request" | "Obligation" | "Payment";
        /** @description All amounts in ETB, ≤2 decimal places (§12.1). */
        Money: {
            /** Format: double */
            amount: number;
            /**
             * @default ETB
             * @enum {string}
             */
            currency: "ETB";
        };
        RegisterRequest: {
            /** @description §12.2.1 — letters, numbers, spaces, hyphens, underscores only. */
            display_name: string;
        };
        UpdateProfileRequest: {
            display_name?: string;
            /** @description Set via a separate photo-upload flow (multer/S3, §11.1.6); this field references the resulting URL. */
            profile_photo_url?: string | null;
        };
        FcmTokenRequest: {
            fcm_token: string;
            /** @enum {string} */
            platform: "android" | "ios" | "web";
        };
        VerifyTelebirrRequest: {
            /** @description §12.2.1 Ethiopian Telebirr format. */
            telebirr_number: string;
        };
        /** @description State of the verification code just sent by `POST /users/me/telebirr/otp`. The code itself is never returned. */
        TelebirrOtpChallenge: {
            /**
             * Format: date-time
             * @description When the code stops being accepted (5 minutes after sending).
             */
            expires_at: string;
            /**
             * Format: date-time
             * @description Earliest time a new code may be requested (60 seconds after sending).
             */
            resend_available_at: string;
        };
        ConfirmTelebirrOtpRequest: {
            /** @description The 6-digit code received by SMS. */
            code: string;
        };
        TelebirrAccount: {
            account_id: string;
            telebirr_number: string | null;
            verification_status: components["schemas"]["TelebirrStatus"];
            /** Format: date-time */
            verified_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UserSummary: {
            user_id: string;
            display_name: string;
            profile_photo_url: string | null;
        };
        User: components["schemas"]["UserSummary"] & {
            /** @description Email or phone used for login/search — sourced from the verified Firebase identity. */
            identifier: string;
            /** @enum {string} */
            verification_status: "Verified";
            /** @description Null until the user completes Telebirr verification (§6.1.3) — not set at registration. */
            telebirr: components["schemas"]["TelebirrAccount"] | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description §12.2.3 — required iff proposed_repayment_type is Installments; 2–60 entries; sum must equal the principal (0.01 ETB tolerance); dates ascending, future, ≤ overall due date. */
        ProposedScheduleInput: {
            installments: {
                amount: components["schemas"]["Money"];
                /** Format: date */
                due_date: string;
            }[];
        };
        /** @description §6.2.1, §12.2.2. Lender sets disbursement_method later, at acceptance. */
        BorrowRequestInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            request_type: "Borrow";
            /** @description The prospective lender. */
            recipient_user_id: string;
            amount: components["schemas"]["Money"];
            purpose: string;
            proposed_repayment_type: components["schemas"]["RepaymentType"];
            proposed_schedule?: components["schemas"]["ProposedScheduleInput"];
            /**
             * Format: date
             * @description ≥1 day in the future, ≤3 years from today (§12.2.2).
             */
            proposed_due_date: string;
        };
        /** @description §6.2.4, §12.2.2. Lender sets disbursement_method at creation. */
        LendRequestInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            request_type: "Lend";
            /** @description The borrower. */
            recipient_user_id: string;
            amount: components["schemas"]["Money"];
            purpose: string;
            proposed_repayment_type: components["schemas"]["RepaymentType"];
            proposed_schedule?: components["schemas"]["ProposedScheduleInput"];
            /** Format: date */
            proposed_due_date: string;
            disbursement_method: components["schemas"]["DisbursementMethod"];
        };
        /** @description Shared body for repayment-request creation, used directly by the convenience endpoint and nested in RepaymentRequestInput. */
        RepaymentRequestBody: {
            /** @description Required (must reference a currently-Overdue installment) for Installments obligations; omit for Lump Sum. */
            installment_id?: string | null;
            note?: string | null;
        };
        RepaymentRequestInput: {
            /** @enum {string} */
            request_type: "Repayment";
            /** @description Set immediately at creation (unlike Borrow/Lend, where obligation_id is set only on acceptance). */
            obligation_id: string;
        } & components["schemas"]["RepaymentRequestBody"] & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            request_type: "Repayment";
        };
        /** @description Same shape/validation as the original proposal for this request's type. */
        CounterProposalInput: {
            amount?: components["schemas"]["Money"];
            proposed_repayment_type?: components["schemas"]["RepaymentType"];
            proposed_schedule?: components["schemas"]["ProposedScheduleInput"];
            /** Format: date */
            proposed_due_date?: string;
        };
        AcceptRequestInput: {
            /** @description Required only when accepting a Borrow request (the lender chooses it here); ignored otherwise. */
            disbursement_method?: components["schemas"]["DisbursementMethod"];
        };
        Request: {
            request_id: string;
            request_type: components["schemas"]["RequestType"];
            initiating_user: components["schemas"]["UserSummary"];
            receiving_user: components["schemas"]["UserSummary"];
            /** @description Null until acceptance for Borrow/Lend; set immediately for Repayment. */
            obligation_id: string | null;
            amount: components["schemas"]["Money"];
            purpose: string | null;
            proposed_repayment_type: components["schemas"]["RepaymentType"] | null;
            proposed_schedule: components["schemas"]["ProposedScheduleInput"] | null;
            /** Format: date */
            proposed_due_date: string | null;
            disbursement_method: components["schemas"]["DisbursementMethod"] | null;
            /** @description Populated once status is Countered. */
            counter_proposal: components["schemas"]["CounterProposalInput"] | null;
            status: components["schemas"]["RequestStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            responded_at: string | null;
        };
        RequestPage: {
            data: components["schemas"]["Request"][];
            next_cursor: string | null;
        };
        Obligation: {
            obligation_id: string;
            borrower: components["schemas"]["UserSummary"];
            lender: components["schemas"]["UserSummary"];
            originating_request_id: string | null;
            originating_expense_id: string | null;
            principal_amount: components["schemas"]["Money"];
            /** @description Zero while Pending Disbursement; equals principal once disbursed; decreases in fixed increments as repayments confirm. */
            outstanding_balance: components["schemas"]["Money"];
            purpose: string;
            repayment_type: components["schemas"]["RepaymentType"];
            disbursement_method: components["schemas"]["DisbursementMethod"];
            /** Format: date */
            due_date: string;
            status: components["schemas"]["ObligationStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            settled_at: string | null;
        };
        ObligationPage: {
            data: components["schemas"]["Obligation"][];
            next_cursor: string | null;
        };
        Installment: {
            installment_id: string;
            amount: components["schemas"]["Money"];
            /** Format: date */
            due_date: string;
            status: components["schemas"]["InstallmentStatus"];
            /** Format: date-time */
            paid_at: string | null;
        };
        RepaymentSchedule: {
            schedule_id: string;
            obligation_id: string;
            installment_count: number;
            status: components["schemas"]["ScheduleStatus"];
            installments: components["schemas"]["Installment"][];
            /** Format: date-time */
            created_at: string;
        };
        InitiateChapaPaymentInput: {
            /** @description Required for a repayment on an Installments obligation; must reference a Pending/Overdue installment (§12.2.4). Omit for Lump Sum or for disbursement. */
            installment_id?: string | null;
        };
        RecordExternalPaymentInput: {
            payment_direction: components["schemas"]["PaymentDirection"];
            /** @description Required for a repayment on an Installments obligation; must reference a Pending/Overdue installment. */
            installment_id?: string | null;
            /**
             * Format: date
             * @description Not in the future; not before the obligation's creation date (§12.2.4).
             */
            payment_date: string;
            external_method_note: components["schemas"]["ExternalPaymentMethodNote"];
            note?: string | null;
        };
        Payment: {
            payment_id: string;
            obligation_id: string;
            installment_id: string | null;
            payer: components["schemas"]["UserSummary"];
            recipient: components["schemas"]["UserSummary"];
            /** @description System-determined, never freely entered (§12.2.4). */
            amount: components["schemas"]["Money"];
            payment_direction: components["schemas"]["PaymentDirection"];
            payment_method: components["schemas"]["PaymentMethod"];
            /** @description External payments only. */
            recorded_by_user_id: string | null;
            external_method_note: components["schemas"]["ExternalPaymentMethodNote"] | null;
            chapa_transaction_id: string | null;
            /** @description Present when a Chapa collection hop is pending. */
            checkout_url: string | null;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            recorded_at: string;
            /** Format: date-time */
            confirmed_at: string | null;
        };
        /** @description §12.2.2 — 1–50 participants; assigned amounts (+ payer's own share, if included) must sum to total within 0.01 ETB. */
        CreateGroupExpenseInput: {
            total_amount: components["schemas"]["Money"];
            description: string;
            /**
             * Format: date
             * @description Must not be in the future.
             */
            expense_date: string;
            /**
             * Format: date
             * @description Repayment due date applied to every spawned obligation — on or after `expense_date`, at most 3 years out. The expense itself has no lifecycle; this is the deadline each participant owes by.
             */
            due_date: string;
            payer_share_included: boolean;
            /** @description Required when payer_share_included is true; omitted when false. */
            payer_share_amount?: components["schemas"]["Money"] | null;
            participants: {
                participant_user_id: string;
                assigned_amount: components["schemas"]["Money"];
            }[];
        };
        GroupExpenseParticipant: {
            participant_entry_id: string;
            participant: components["schemas"]["UserSummary"];
            assigned_amount: components["schemas"]["Money"];
            obligation_id: string;
        };
        GroupExpense: {
            expense_id: string;
            payer: components["schemas"]["UserSummary"];
            total_amount: components["schemas"]["Money"];
            description: string;
            /** Format: date */
            expense_date: string;
            /**
             * Format: date
             * @description Due date carried onto every spawned obligation.
             */
            due_date: string;
            payer_share_included: boolean;
            /** @description Recorded for accounting completeness only — no obligation is ever created against it. */
            payer_share_amount: components["schemas"]["Money"] | null;
            participants: components["schemas"]["GroupExpenseParticipant"][];
            /** Format: date-time */
            created_at: string;
        };
        SettlementSuggestion: {
            suggestion_id?: string;
            user_a?: components["schemas"]["UserSummary"];
            user_b?: components["schemas"]["UserSummary"];
            /** @description Active obligation where user_a is the borrower. */
            obligation_id_a?: string;
            /** @description Active obligation where user_b is the borrower. */
            obligation_id_b?: string;
            net_amount?: components["schemas"]["Money"];
            net_payer?: components["schemas"]["UserSummary"];
            net_recipient?: components["schemas"]["UserSummary"];
            user_a_response?: components["schemas"]["SettlementResponse"];
            user_b_response?: components["schemas"]["SettlementResponse"];
            status?: components["schemas"]["SettlementResponse"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            resolved_at?: string | null;
        };
        ObligationHistoryEntry: {
            history_id?: string;
            obligation_id?: string;
            event_type?: components["schemas"]["ObligationHistoryEventType"];
            initiated_by?: components["schemas"]["UserSummary"];
            /** @description Serialized description of the event (amounts, previous/new values, etc.). */
            event_detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurred_at?: string;
        };
        Notification: {
            notification_id?: string;
            /** @description Event that triggered the notification, e.g. New Request, Payment Confirmed, Change Proposed — see §13.2 event catalog. */
            notification_type?: string;
            reference_id?: string;
            reference_type?: components["schemas"]["NotificationReferenceType"];
            is_read?: boolean;
            /** Format: date-time */
            delivered_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Shape intentionally minimal pending §6.1.5 UI design — extend as concrete toggles are defined. */
        NotificationPreferences: {
            push_enabled?: boolean;
        };
    };
    responses: {
        /** @description One or more input fields failed validation (§12.3.2 `VALIDATION_ERROR`). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "The due date must be a future date.",
                 *         "field": "proposed_due_date"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid session token (§12.3.2 `UNAUTHENTICATED`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHENTICATED",
                 *         "message": "Your session has expired. Please log in again."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not a party to this record (§12.3.2 `UNAUTHORIZED`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Record does not exist or is not accessible to this user (§12.3.2 `NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The record's current status does not allow this operation (§12.3.2 `STATUS_CONFLICT`). */
        StatusConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Cursor: string;
        UserId: string;
        RequestId: string;
        ObligationId: string;
        PaymentId: string;
        GroupExpenseId: string;
        SuggestionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /** @description Token is valid but no BuryMe user exists yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            /** @description A profile already exists for this identity. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerFcmToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FcmTokenRequest"];
            };
        };
        responses: {
            /** @description Token stored. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    deleteFcmToken: {
        parameters: {
            query: {
                fcm_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed (or was already absent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                q: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getTelebirr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telebirr account state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelebirrAccount"];
                };
            };
        };
    };
    verifyTelebirr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyTelebirrRequest"];
            };
        };
        responses: {
            /** @description Updated Telebirr account state (Unverified while verification is in progress). Call `POST /users/me/telebirr/otp` next to start OTP verification of the saved number. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelebirrAccount"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    sendTelebirrOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelebirrOtpChallenge"];
                };
            };
            /** @description No Telebirr number is saved yet, or the account is already Verified (`STATUS_CONFLICT`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A code was sent less than 60 seconds ago (`DUPLICATE_SUBMISSION`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmTelebirrOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmTelebirrOtpRequest"];
            };
        };
        responses: {
            /** @description Telebirr account now `Verified`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelebirrAccount"];
                };
            };
            /** @description Wrong or expired code (`VALIDATION_ERROR`, field `code`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No verification is pending, attempts are exhausted, or the account is already Verified (`STATUS_CONFLICT`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRequests: {
        parameters: {
            query?: {
                /** @description Filter by the current user's role on the request. */
                role?: "initiator" | "recipient";
                /** @description Comma-separated RequestStatus values. */
                status?: string;
                request_type?: components["schemas"]["RequestType"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BorrowRequestInput"] | components["schemas"]["LendRequestInput"] | components["schemas"]["RepaymentRequestInput"];
            };
        };
        responses: {
            /** @description Request created with status `Pending`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description An open request already exists, or the Repayment target isn't actually overdue. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    counterRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterProposalInput"];
            };
        };
        responses: {
            /** @description Request updated with the counter-proposal, status `Countered`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["StatusConflict"];
        };
    };
    acceptRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptRequestInput"];
            };
        };
        responses: {
            /** @description Updated request (now `Accepted`), with `obligation_id` populated for Borrow/Lend. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            409: components["responses"]["StatusConflict"];
        };
    };
    declineRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request moved to `Declined`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            409: components["responses"]["StatusConflict"];
        };
    };
    cancelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request moved to `Cancelled`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            403: components["responses"]["Unauthorized"];
            409: components["responses"]["StatusConflict"];
        };
    };
    listObligations: {
        parameters: {
            query?: {
                role?: "lender" | "borrower";
                /** @description Comma-separated ObligationStatus values. */
                status?: string;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of obligations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationPage"];
                };
            };
        };
    };
    getObligation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Obligation detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Obligation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    disburseObligation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment created with a live `checkout_url`; obligation remains `Pending Disbursement`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description Caller is not the lender (`UNAUTHORIZED`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not in `Pending Disbursement` (`STATUS_CONFLICT`), borrower not yet Telebirr-verified (`RECIPIENT_UNVERIFIED`), or a disbursement payment is already in progress (`DUPLICATE_SUBMISSION`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Chapa could not open the checkout session (`PAYMENT_GATEWAY_ERROR`); the payment is marked `Failed`. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRepaymentRequestForObligation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepaymentRequestBody"];
            };
        };
        responses: {
            /** @description Repayment request created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            /** @description Nothing on this obligation is currently overdue. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repayment schedule with its installments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepaymentSchedule"];
                };
            };
            /** @description Obligation is Lump Sum and has no schedule. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPayments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All payments (both directions, both methods) on this obligation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"][];
                };
            };
        };
    };
    initiateChapaPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiateChapaPaymentInput"];
            };
        };
        responses: {
            /** @description Payment record created (`Pending Acknowledgement` until webhook confirms); includes checkout URL when a collection hop applies. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Selected installment already paid, or recipient not Telebirr-verified. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    recordExternalPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordExternalPaymentInput"];
            };
        };
        responses: {
            /** @description Payment recorded, `Pending Acknowledgement`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Selected installment already paid. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    acknowledgePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment `Confirmed`; obligation balance updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            409: components["responses"]["StatusConflict"];
        };
    };
    disputePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment `Disputed`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            409: components["responses"]["StatusConflict"];
        };
    };
    chapaCheckoutWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chapaTransferWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroupExpenses: {
        parameters: {
            query?: {
                role?: "payer" | "participant";
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of group expenses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GroupExpense"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    createGroupExpense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupExpenseInput"];
            };
        };
        responses: {
            /** @description Group expense created with its participant obligations. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupExpense"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getGroupExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupExpenseId: components["parameters"]["GroupExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group expense detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupExpense"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSettlementSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestions involving the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementSuggestion"][];
                };
            };
        };
    };
    getSettlementSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestionId: components["parameters"]["SuggestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestion detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementSuggestion"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    acceptSettlementSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestionId: components["parameters"]["SuggestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated suggestion (still `Pending` if awaiting the other party, or `Accepted`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementSuggestion"];
                };
            };
            /** @description One of the paired obligations was already settled by other means. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    declineSettlementSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestionId: components["parameters"]["SuggestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestion `Declined`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementSuggestion"];
                };
            };
        };
    };
    getObligationHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligationId: components["parameters"]["ObligationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History entries, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationHistoryEntry"][];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of notifications, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Notification"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Omit to mark all as read. */
                    notification_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Marked read. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferences"];
            };
        };
        responses: {
            /** @description Updated preferences. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
        };
    };
}
